# Generated by Django 5.1.1 on 2024-10-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_content_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
